baseURL = "https://datablets.com/"
languageCode = "en-gb"
title = "datablets"
theme = "paperesque"

[params]
description = "Easy to swallow data science"
favicon = "#"
rss = false
socialShare = true
wordCount = true

[[params.menu]]
name = "all posts"
url = "posts/"

[[params.menu]]
name = "posts by topic"
url = "topics/"

# [[params.menu]]
# name = "about"
# url = "about/"

# [[params.menu]]
# name = "contact"
# url = "contact/"


# Removing original images after resizing (originals to be removed from the output.)
[outputs]
page = ["HTML", "droplist"] 